name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_call:
    inputs: 
      DOCKER_REGISTRY:
        required: false
        type: string
        default: ''
        
    secrets:
      VAULT_ROLE_ID:
        required: true 
      VAULT_SECRET_ID:
        required: true 
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      # - name: Import Secrets
      #   uses: hashicorp/vault-action@v2.4.2
      #   id: secrets
      #   with:
      #     url: https://vault.k8sdemo.tk
      #     method: approle
      #     roleId: ${{ secrets.VAULT_ROLE_ID }}
      #     secretId: ${{ secrets.VAULT_SECRET_ID }}
      #     secrets: |
      #       kv/data/${{ env.DOCKER_REGISTRY }}/v2 username | USERNAME ;
      #       kv/data/${{ env.DOCKER_REGISTRY }}/v2 password | PASSWORD     
      - name: docker login custom action - 4
        uses: bansodesatish/actions/docker-login@main
        id: secrets
        with:
          DOCKER_REGISTRY: ${{ inputs.DOCKER_REGISTRY }}
          VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
          VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
      # - name: docker login
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ env.DOCKER_REGISTRY }}
      #     username: ${{ steps.secrets.outputs.USERNAME }}
      #     password: ${{ steps.secrets.outputs.PASSWORD }}  